Add devise
jaimevillegas/rails-blog-app pull request #9
Opened 2023-06-21 15:03 UTC by jaimevillegas

Hi there!

@SFarida and I have made the following changes to the repository:

- Add devise authentication following project requirements

Thank you a lot for taking the time to review our code! 🚀 ✨ ⚡

2023-06-21 23:27 UTC, jerryowusu requested changes
Hi Team

Good job so far!
Your project is looking fantastic so far :star_struck: 

However, there are few changes you need to make in order to move on to the next level :sunglasses:

![so-close](https://github.com/jaimevillegas/rails-blog-app/assets/65233860/bcbfb6fc-36ec-45b1-8009-8af6c1c2cebb)


## Highlights
Used devise gem :+1: 
Neat and well organized code :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-21 23:27 UTC, jerryowusu commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable, :confirmable
It looks like the app is having issues with password confirmation when you try to create a new user. I tried creating a new user without the `:confirmable` and it worked fine. However, with `:confirmable`, it does not work but throws an error as shown below :point_down: 
Kindly fix it and make sure it works well with no errors. 

![Screenshot from 2023-06-21 23-22-36](https://github.com/jaimevillegas/rails-blog-app/assets/65233860/d6e3cbbe-f4bc-4502-bc02-2012f415a8e2)

2023-06-22 13:52 UTC, jaimevillegas commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable, :confirmable
Hello @jerryowusu 

Thank you so much to review our code!

We have worked on that. We've added a migration to add the column `confirmed_at` and other ones requested by confirmable. Now it works as expected. 🚀 ✨

2023-06-22 14:15 UTC, ShadyShawkat requested changes
## Hi @jaimevillegas, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![Image](https://c.tenor.com/CWrSBML0hC8AAAAC/little-dinosaur-so-close.gif)

 ## Required Changes ♻️
- [ ] Kindly make sure to fix all errors which prevent the app from working properly. Currently, when I tried to run the migrations I got the following list of errors. You can simulate this by dropping, creating, and then setting up the database and you should get these errors.
![image](https://github.com/jaimevillegas/rails-blog-app/assets/62290545/fe5aee5a-af49-471a-9be0-c786bd69c638)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-22 14:41 UTC, jaimevillegas commented
Hello @ShadyShawkat 

Thank you for your comment!

We had an error with the migration, but now it's done. I have dropped and created all again, and migration runs without errors. Now I can enter `users/sign_up` and create an account or log in to access the blog app! ⚡

2023-06-22 14:56 UTC, TadesseDev requested changes
### Hi @jaimevillegas 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![199733072-bdacca19-8df9-43a7-be93-3aff2f1c15c8](https://user-images.githubusercontent.com/69077061/204107907-c2532abb-b23d-4fda-88f0-1ec9c7b71971.gif)

 ## Highlights
 - [x] Good job making most of the changes requested by the previous reviewer. 🙏


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-22 14:56 UTC, TadesseDev commented on app/controllers/application_controller.rb
> +  protect_from_forgery with: :exception
- [ ] You have done an incredible job adding the migration and fixing the errors. Thanks to your changes now it's possible to get to the login and sign-up pages. But the design of your `login` page is not following the wireframe provided. 

### Your design 
![image](https://github.com/jaimevillegas/rails-blog-app/assets/69077061/37daf47d-cf58-4248-a18e-2f47945df512)

### Wireframe 
![blog_login](https://github.com/jaimevillegas/rails-blog-app/assets/69077061/be349d72-4824-4ecd-9cf1-e4375eeb2c94)

- [Optional] I would suggest making your `Login` route your `root` path, this makes it easy for the user to sign in. I had to check out your routes to find the route for the login page.

2023-06-22 15:14 UTC, jaimevillegas commented on app/controllers/application_controller.rb
> +  protect_from_forgery with: :exception
Hello @TadesseDev 

Thank you so much for your comments!

The design now matches the wireframe:
![image](https://github.com/jaimevillegas/rails-blog-app/assets/5252636/a197b831-ae96-490b-8879-c695648fb8e0)

2023-06-22 15:23 UTC, thecodechaser approved these changes
## STATUS: APPROVED 🟢

## Hi @jaimevillegas, and @SFarida👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉
- Good job with authentication. ✔️
- No linter errors. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-22 15:26 UTC, merged